name: Build and Publish nuget package (Manual Versioning)

on:
  workflow_dispatch:
    
permissions:
  contents: read
  packages: write # Required for publishing
  
jobs:
  core-package:
    runs-on: ubuntu-latest
    outputs:
      core-version: ${{steps.get-version-core.outputs.version}}
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Dgraph.sln'
      CORE_NAME: 'Dgraph'
      CORE_PROJECT: 'source/Dgraph/Dgraph.csproj'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Ensures we fetch all history for all branches and tags

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Set up NuGet packages source
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.RUNNER_TOKEN_PRIVATE_NPM_READ }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Leadr-HR/index.json"

      - name: Restore dependencies Core
        run: dotnet restore ${{ env.CORE_PROJECT }}

      - name: Retrieve New Version Core
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: get-version-core
        with:
          proj-path: ${{ env.CORE_PROJECT }}

      - name: Build Core
        run: |
          dotnet build ${{ env.CORE_PROJECT }} --configuration Release
          dotnet pack ${{ env.CORE_PROJECT }} --configuration Release

      - name: Publish Core
        run: dotnet nuget push "**/${{ env.CORE_NAME }}*.nupkg" -k ${{ secrets.RUNNER_TOKEN_PRIVATE_NPM_PUBLISH }} -s https://nuget.pkg.github.com/Leadr-HR/index.json --skip-duplicate